# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: npm install --global http-server
    init: echo 'init script' # runs during prebuild
    command: http-server --cors
  - init: yarn install && yarn run build
    command: yarn run start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
